//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_v9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int Id { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
       // [Display(Name ="PickUpDate")]
        [DisplayFormat  (DataFormatString = "{0:dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime PickUpDate { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime DropOffDate { get; set; }
        public int CarsId { get; set; }
        public string AspNetUserId { get; set; }
        public int PickDropLocId { get; set; }
    
        public virtual Cars Car { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PickDropLoc PickDropLoc { get; set; }
    }
}
