//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_v9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Feedback
    {
        public int Id { get; set; }
        [Required]
        [Range(1,5)]
        public double Rating { get; set; }
        [AllowHtml]
        [Required]
        public string Comments { get; set; }
    }
}
