//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_v9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickDropLoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickDropLoc()
        {
            this.Cars = new HashSet<Cars>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string LocStreet { get; set; }
        public string LocSuburb { get; set; }
        public string LocState { get; set; }
        public string Landmark { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
